# LoginPage.py
"""
Page Object for the Login Page of Example E-Commerce.

This class encapsulates all UI elements and actions for the login page, using locators defined in Locators.json.

Generated by Test Automation Orchestration Agent.

Features:
- All locators from Locators.json represented as properties/methods.
- Comprehensive docstrings for downstream automation.
- Strict code integrity and structure for enterprise usage.

Usage Example:
    login_page = LoginPage(driver)
    login_page.open()
    login_page.enter_email('user@example.com')
    login_page.enter_password('securepassword')
    login_page.toggle_remember_me(True)
    login_page.submit()
    assert login_page.is_dashboard_loaded()

"""

from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class LoginPage:
    """
    Page Object Model for Login Page.
    """
    URL = "https://example-ecommerce.com/login"

    # Locators
    EMAIL_FIELD = (By.ID, "login-email")
    PASSWORD_FIELD = (By.ID, "login-password")
    REMEMBER_ME_CHECKBOX = (By.ID, "remember-me")
    LOGIN_SUBMIT = (By.ID, "login-submit")
    FORGOT_PASSWORD_LINK = (By.CSS_SELECTOR, "a.forgot-password-link")
    ERROR_MESSAGE = (By.CSS_SELECTOR, "div.alert-danger")
    VALIDATION_ERROR = (By.CSS_SELECTOR, ".invalid-feedback")
    EMPTY_FIELD_PROMPT = (By.XPATH, "//*[text()='Mandatory fields are required']")
    DASHBOARD_HEADER = (By.CSS_SELECTOR, "h1.dashboard-title")
    USER_PROFILE_ICON = (By.CSS_SELECTOR, ".user-profile-name")

    def __init__(self, driver: WebDriver):
        """
        Initialize LoginPage with WebDriver instance.
        """
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)

    def open(self):
        """
        Navigate to the login page URL.
        """
        self.driver.get(self.URL)

    def enter_email(self, email: str):
        """
        Enter email into the email field.
        """
        email_input = self.wait.until(EC.visibility_of_element_located(self.EMAIL_FIELD))
        email_input.clear()
        email_input.send_keys(email)

    def enter_password(self, password: str):
        """
        Enter password into the password field.
        """
        password_input = self.wait.until(EC.visibility_of_element_located(self.PASSWORD_FIELD))
        password_input.clear()
        password_input.send_keys(password)

    def toggle_remember_me(self, enable: bool):
        """
        Set the 'Remember Me' checkbox to the desired state.
        """
        checkbox = self.wait.until(EC.element_to_be_clickable(self.REMEMBER_ME_CHECKBOX))
        if checkbox.is_selected() != enable:
            checkbox.click()

    def submit(self):
        """
        Click the login submit button.
        """
        submit_btn = self.wait.until(EC.element_to_be_clickable(self.LOGIN_SUBMIT))
        submit_btn.click()

    def click_forgot_password(self):
        """
        Click the 'Forgot Password' link.
        """
        link = self.wait.until(EC.element_to_be_clickable(self.FORGOT_PASSWORD_LINK))
        link.click()

    def get_error_message(self) -> str:
        """
        Retrieve error message text if present.
        """
        try:
            error = self.wait.until(EC.visibility_of_element_located(self.ERROR_MESSAGE))
            return error.text
        except:
            return ""

    def get_validation_error(self) -> str:
        """
        Retrieve validation error text if present.
        """
        try:
            error = self.wait.until(EC.visibility_of_element_located(self.VALIDATION_ERROR))
            return error.text
        except:
            return ""

    def is_empty_field_prompt_displayed(self) -> bool:
        """
        Check if the empty field prompt is displayed.
        """
        try:
            prompt = self.wait.until(EC.visibility_of_element_located(self.EMPTY_FIELD_PROMPT))
            return True
        except:
            return False

    def is_dashboard_loaded(self) -> bool:
        """
        Check if dashboard header is visible post-login.
        """
        try:
            header = self.wait.until(EC.visibility_of_element_located(self.DASHBOARD_HEADER))
            return True
        except:
            return False

    def is_user_profile_icon_visible(self) -> bool:
        """
        Check if user profile icon is visible post-login.
        """
        try:
            icon = self.wait.until(EC.visibility_of_element_located(self.USER_PROFILE_ICON))
            return True
        except:
            return False

    # Additional methods can be added as required by future test cases.
