# RuleManagementPage.py
"""
Page Object for Rule Management Page.

This class encapsulates UI elements and actions for managing rules with triggers and actions such as specific_date, recurring, fixed_amount, percentage_of_deposit.

Generated by Test Automation Orchestration Agent.

Features:
- Locators mapped from Locators.json and test case requirements.
- Methods for creating, updating, and validating rules.
- Comprehensive docstrings for downstream automation.
- Strict code integrity and structure for enterprise usage.

Usage Example:
    rule_page = RuleManagementPage(driver)
    rule_page.open()
    rule_page.create_rule({
        'name': 'Recurring Deposit',
        'trigger': 'recurring',
        'action': 'percentage_of_deposit',
        'value': 10,
        'date': '2024-07-01'
    })
    assert rule_page.is_rule_created('Recurring Deposit')

"""

from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class RuleManagementPage:
    """
    Page Object Model for Rule Management Page.
    """
    URL = "https://example-ecommerce.com/rules"

    # Locators (example, should match Locators.json)
    CREATE_RULE_BUTTON = (By.ID, "create-rule-btn")
    RULE_NAME_FIELD = (By.ID, "rule-name-input")
    TRIGGER_DROPDOWN = (By.ID, "trigger-dropdown")
    ACTION_DROPDOWN = (By.ID, "action-dropdown")
    VALUE_FIELD = (By.ID, "rule-value-input")
    DATE_PICKER = (By.ID, "rule-date-picker")
    SAVE_BUTTON = (By.ID, "save-rule-btn")
    SUCCESS_MESSAGE = (By.CSS_SELECTOR, "div.alert-success")
    RULE_LIST = (By.CSS_SELECTOR, "ul.rules-list")

    def __init__(self, driver: WebDriver):
        """
        Initialize RuleManagementPage with WebDriver instance.
        """
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)

    def open(self):
        """
        Navigate to the rule management page URL.
        """
        self.driver.get(self.URL)

    def create_rule(self, rule_data: dict):
        """
        Create a new rule with provided data.
        Args:
            rule_data (dict): {'name', 'trigger', 'action', 'value', 'date'}
        """
        self.wait.until(EC.element_to_be_clickable(self.CREATE_RULE_BUTTON)).click()
        self.wait.until(EC.visibility_of_element_located(self.RULE_NAME_FIELD)).send_keys(rule_data['name'])
        self.wait.until(EC.element_to_be_clickable(self.TRIGGER_DROPDOWN)).click()
        self.select_dropdown_option(self.TRIGGER_DROPDOWN, rule_data['trigger'])
        self.wait.until(EC.element_to_be_clickable(self.ACTION_DROPDOWN)).click()
        self.select_dropdown_option(self.ACTION_DROPDOWN, rule_data['action'])
        self.wait.until(EC.visibility_of_element_located(self.VALUE_FIELD)).send_keys(str(rule_data['value']))
        if 'date' in rule_data:
            self.wait.until(EC.visibility_of_element_located(self.DATE_PICKER)).send_keys(rule_data['date'])
        self.wait.until(EC.element_to_be_clickable(self.SAVE_BUTTON)).click()

    def select_dropdown_option(self, dropdown_locator, option_text):
        """
        Select an option from dropdown by visible text.
        """
        dropdown = self.wait.until(EC.visibility_of_element_located(dropdown_locator))
        for option in dropdown.find_elements_by_tag_name('option'):
            if option.text == option_text:
                option.click()
                break

    def is_rule_created(self, rule_name: str) -> bool:
        """
        Check if rule with given name is present in rule list.
        """
        rule_list = self.wait.until(EC.visibility_of_element_located(self.RULE_LIST))
        return any(rule_name in item.text for item in rule_list.find_elements_by_tag_name('li'))

    def get_success_message(self) -> str:
        """
        Retrieve success message after rule creation.
        """
        try:
            msg = self.wait.until(EC.visibility_of_element_located(self.SUCCESS_MESSAGE))
            return msg.text
        except:
            return ""

    # Additional methods for update, delete, validate can be added as required by future test cases.
