# TransactionPage.py
"""
Page Object for Transaction Page.

This class encapsulates UI elements and actions for transaction operations, including triggers and actions relevant to rules (fixed_amount, percentage_of_deposit).

Generated by Test Automation Orchestration Agent.

Features:
- Locators mapped from Locators.json and test case requirements.
- Methods for performing and validating transactions.
- Comprehensive docstrings for downstream automation.
- Strict code integrity and structure for enterprise usage.

Usage Example:
    transaction_page = TransactionPage(driver)
    transaction_page.open()
    transaction_page.perform_transaction({
        'amount': 100,
        'type': 'deposit',
        'percentage': 10
    })
    assert transaction_page.is_transaction_successful()

"""

from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TransactionPage:
    """
    Page Object Model for Transaction Page.
    """
    URL = "https://example-ecommerce.com/transactions"

    # Locators (example, should match Locators.json)
    NEW_TRANSACTION_BUTTON = (By.ID, "new-transaction-btn")
    AMOUNT_FIELD = (By.ID, "transaction-amount-input")
    TYPE_DROPDOWN = (By.ID, "transaction-type-dropdown")
    PERCENTAGE_FIELD = (By.ID, "transaction-percentage-input")
    SUBMIT_BUTTON = (By.ID, "submit-transaction-btn")
    SUCCESS_MESSAGE = (By.CSS_SELECTOR, "div.alert-success")
    TRANSACTION_LIST = (By.CSS_SELECTOR, "ul.transaction-list")

    def __init__(self, driver: WebDriver):
        """
        Initialize TransactionPage with WebDriver instance.
        """
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)

    def open(self):
        """
        Navigate to the transaction page URL.
        """
        self.driver.get(self.URL)

    def perform_transaction(self, transaction_data: dict):
        """
        Perform a new transaction with provided data.
        Args:
            transaction_data (dict): {'amount', 'type', 'percentage'}
        """
        self.wait.until(EC.element_to_be_clickable(self.NEW_TRANSACTION_BUTTON)).click()
        self.wait.until(EC.visibility_of_element_located(self.AMOUNT_FIELD)).send_keys(str(transaction_data['amount']))
        self.wait.until(EC.element_to_be_clickable(self.TYPE_DROPDOWN)).click()
        self.select_dropdown_option(self.TYPE_DROPDOWN, transaction_data['type'])
        if 'percentage' in transaction_data:
            self.wait.until(EC.visibility_of_element_located(self.PERCENTAGE_FIELD)).send_keys(str(transaction_data['percentage']))
        self.wait.until(EC.element_to_be_clickable(self.SUBMIT_BUTTON)).click()

    def select_dropdown_option(self, dropdown_locator, option_text):
        """
        Select an option from dropdown by visible text.
        """
        dropdown = self.wait.until(EC.visibility_of_element_located(dropdown_locator))
        for option in dropdown.find_elements_by_tag_name('option'):
            if option.text == option_text:
                option.click()
                break

    def is_transaction_successful(self) -> bool:
        """
        Check if success message is displayed after transaction.
        """
        try:
            msg = self.wait.until(EC.visibility_of_element_located(self.SUCCESS_MESSAGE))
            return True
        except:
            return False

    def get_transaction_list(self) -> list:
        """
        Retrieve list of transactions.
        """
        transaction_list = self.wait.until(EC.visibility_of_element_located(self.TRANSACTION_LIST))
        return [item.text for item in transaction_list.find_elements_by_tag_name('li')]

    # Additional methods for transaction validation can be added as required by future test cases.
